name: Build and deploy ASP.Net Core app to Azure Web App - dotnet-github-actions
on:
  push:
    branches:
      - test
  workflow_dispatch:
jobs:  
  build:  
    name: Test and publish
    
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v3
        - name: clone other repo
          run: |
            mkdir accounting && cd accounting
            git clone https://github.com/chandrasekhar7/account.git
            ls


