name: Build and deploy ASP.Net Core app to Azure Web App - dotnet-github-actions
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:  
  build:  
    name: Test and publish
    
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v3
        - name: Setup dotnet
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: 6.0.x
        - name: Install dependencies
          run: dotnet restore
        - name: Install build
          run: dotnet build Npa.Accounting.sln --configuration Release
        - name: publish the artifacts
          run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/account-rest-service
        - name: Upload Build Artifacts
          uses: actions/upload-artifact@v3
          with:
            name: account-rest-service
            path: ${{env.DOTNET_ROOT}}/account-rest-service
         
        - name: Download artifact to local system
          uses: actions/download-artifact@v2
          with:
            name: account-rest-service # name of the artifact uploaded in the previous step
            path: D:\mywork\test # path where the artifact will be downloaded

