name: Deploy to Nginx Server

on:
  push:
    branches: [main]

jobs:
  setup-nginx-server:
    runs-on: windows-latest
    steps:
      - name: Download Nginx
        run: Invoke-WebRequest -Uri "https://nginx.org/download/nginx-1.20.0.zip" -OutFile "$env:USERPROFILE\Downloads\nginx.zip" -UseBasicParsing

      - name: Extract Nginx
        run: Expand-Archive "$env:USERPROFILE\Downloads\nginx.zip" -DestinationPath "$env:USERPROFILE\nginx"

      - name: Configure Nginx
        run: |
          #Remove-Item "$env:USERPROFILE\nginx\conf\nginx.conf"
          Copy-Item -Path /path/to/nginx.conf -Destination "$env:USERPROFILE\nginx\conf\nginx.conf"
          & "$env:USERPROFILE\nginx\nginx.exe" -t
          & "$env:USERPROFILE\nginx\nginx.exe"

  deploy-dotnet-app:
    runs-on: windows-latest
    needs: setup-nginx-server
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build and Publish
        run: dotnet publish -c Release -o $(Build.ArtifactStagingDirectory)
