name: Build
on:
  push:
    branches:
      - main # or the name of your main branch
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Setup NuGet.exe for use with actions
        uses: NuGet/setup-nuget@v1.0.6
        with:
          nuget-version: '6.0'
        

      
