name: Deploy to Nginx Server

on:
  push:
    branches: [main]

jobs:
  setup-nginx-server:
    runs-on: ubuntu-latest
    steps:
      - name: Install Nginx
        run: sudo apt-get update && sudo apt-get install -y nginx

      - name: Configure Nginx
        run: |
          sudo rm -f /etc/nginx/sites-enabled/default
          sudo cp /path/to/nginx.conf /etc/nginx/sites-available/myapp.conf
          sudo ln -s /etc/nginx/sites-available/myapp.conf /etc/nginx/sites-enabled/
          sudo nginx -t
          sudo systemctl restart nginx

  deploy-dotnet-app:
    runs-on: self-hosted
    needs: setup-nginx-server
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build and Publish
        run: dotnet publish -c Release -o $(Build.ArtifactStagingDirectory)
