name: Build
on:
  push:
    branches:
      - main # or the name of your main branch
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: checkout
      - uses: actions/checkout@v2
      - name: Setup NuGet.exe for use with actions
  # You may pin to the exact commit or the version.
  # uses: NuGet/setup-nuget@b2bc17b761a1d88cab755a776c7922eb26eefbfa
        uses: NuGet/setup-nuget@v1.0.6
        with:
                # NuGet version to install. Can be `latest`, `preview`, a concrete version like `5.3.1`, or a semver range specifier like `5.x`.
          nuget-version: '6.0'
          run: dotnet restore Npa.Accounting.sln

      
