name: test
on:
  push:
    branches:
    - main
jobs:
  build:
    name: chandra
    runs-on: windows-latest
    steps:
      - name: displaying
        run: |
          echo "hellow world"
      - name: sending notification
        if: always()
        uses: cinotify/github-action@main
        with:
          to: 'chandraarlagadda@nuvative.com'
          subject: 'building main'
          body: '<em>This is a notification from GitHub actions.</em>'
          type: 'text/html'
          attachment: 'artifacts.zip'
    
